### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets'

### ISSUE THREAD

**Issue by Zhang-Henry** [Django-Jiang/BadChain#2]
Traceback (most recent call last):
  File "/common/users/hz624/BadChain/run.py", line 121, in <module>
    run(args)
  File "/common/users/hz624/BadChain/run.py", line 18, in run
    questions, answers = task_selection(args.task, args.index, args.rand)
  File "/common/users/hz624/BadChain/utils.py", line 235, in task_selection
    from datasets import load_dataset
ModuleNotFoundError: No module named 'datasets'

Hi, great work! But dataset files are missing.

**Comment by Django-Jiang** [comment]
Hi @Zhang-Henry,

Glad that our work may help you!

I think you may miss the huggingface datasets module (check out [here](https://huggingface.co/docs/datasets/en/installation)).

As I did not plan to make the work highly depend on the specific data path setup, so I did not include that in the initial release. But for the sake of easier usage of our code for you (and other people), I included the dataset files in the last commit. Feel free to use any dataset you like : )
